---
title: "Project"
author: "Cole Foster and Zoey Lee"
date: "2024-03-23"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Setup

```{r, message=FALSE, warning=FALSE}
#Clear workspace
rm(list = ls())

#Set working directory
setwd("C:/Users/colef/OneDrive - University of Miami/Documents/College/Spring 2024/Stat Learning/Project/Data")

library(dplyr)
library(caTools)
library(caret)
library(glmnet)
library(pls)
library(randomForest)
library(gbm)
library(rpart)
library(e1071)
library(verification)
library(pROC)
library(plyr)
library(MLmetrics)

#Load data
passing_data <- read.csv("nfl_passing.csv")
passing_data <- predict(preProcess(passing_data,method=c("range")),passing_data)
rushing_data <- read.csv("nfl_rushing.csv")
rushing_data <- predict(preProcess(rushing_data,method=c("range")),rushing_data)
receiving_data <- read.csv("nfl_receiving.csv")
receiving_data <- predict(preProcess(receiving_data,method=c("range")),receiving_data)

#Split into test and training
passing_sample <- sample.split(passing_data$pro_bowl, SplitRatio = 0.8)
pass_train <- subset(passing_data, passing_sample == TRUE)
pass_test <-  subset(passing_data, passing_sample == FALSE)

rushing_sample <- sample.split(rushing_data$pro_bowl, SplitRatio = 0.8)
rush_train <- subset(rushing_data, rushing_sample == TRUE)
rush_test <-  subset(rushing_data, rushing_sample == FALSE)

receiving_sample <- sample.split(receiving_data$pro_bowl, SplitRatio = 0.8)
receive_train <- subset(receiving_data, receiving_sample == TRUE)
receive_test <-  subset(receiving_data, receiving_sample == FALSE)
```

### Passing

```{r}
#SVM (radial)
tune.out=tune(svm,pro_bowl~Pass.Yds+Yds.Att+Att+Cmp+Cmp..+TD+INT+Rate+X1st+X1st.+X20.+X40.+Lng+Sck+SckY,data=pass_train,kernel="radial",ranges=list(cost=c(0.1,1,10,100,1000),gamma=c(0.5,1,2,3,4)))
radial_bestmod=tune.out$best.model

#Compute Performance
predictions <- predict(radial_bestmod,pass_test)
my_roc <- roc(pass_test$pro_bowl, predictions)
best_roc <- coords(my_roc, "best", ret = "threshold")
SVM_conf <- confusionMatrix(as.factor(pass_test$pro_bowl),as.factor(round(predictions+0.5-best_roc$threshold)))

#LDA
lda_model = lda(pro_bowl~Pass.Yds+Yds.Att+Att+Cmp+Cmp..+TD+INT+Rate+X1st+X1st.+X20.+X40.+Lng+Sck+SckY,data=pass_train)

#Compute Performance
lda_predictions <- predict(lda_model,pass_test)
lda_conf <- confusionMatrix(lda_predictions$class,as.factor(pass_test$pro_bowl))

#RF
RF <- randomForest(as.factor(pro_bowl)~Pass.Yds+Yds.Att+Att+Cmp+Cmp..+TD+INT+Rate+X1st+X1st.+X20.+X40.+Lng+Sck+SckY,data=pass_train, method='class',ntree=1000)

#Compute Performance
RF_predictions <- predict(RF,pass_test,type='class')
RF_conf <- confusionMatrix(RF_predictions,as.factor(pass_test$pro_bowl))
```

```{r}
#Compute new pro bowl selections (Modify the lines below to test different models)
output <- predict(RF,passing_data)

#output <- round(output+0.5-best_roc$threshold)
#output <- as.numeric(output$class)-1
output <- as.numeric(output)-1

#Store player pro bowl selections
updated_passing <- data.frame(Player = integer(length(passing_data$Player)),pro_bowl = integer(length(passing_data$pro_bowl)))
updated_passing$Player <- passing_data$Player
updated_passing$pro_bowl <- output

passing <- data.frame(Player = integer(length(updated_passing$Player)),pro_bowl = integer(length(updated_passing$pro_bowl)))
passing$Player <- passing_data$Player
passing$pro_bowl <- passing_data$pro_bowl

updated_passing <- ddply(updated_passing,~Player,summarise,pro_bowl=sum(pro_bowl))
passing <- ddply(passing,~Player,summarise,pro_bowl=sum(pro_bowl))

#Compare adjusted pro bowls to real pro bowls
passing_diff <- data.frame(Player = integer(length(updated_passing$Player)),pro_bowl = integer(length(updated_passing$pro_bowl)))
passing_diff$pro_bowl <-  updated_passing$pro_bowl - passing$pro_bowl
passing_diff$Player <- passing$Player
print(sum(passing_diff$pro_bowl))
```

### Rushing

```{r}
#SVM (radial)
tune.out=tune(svm,pro_bowl~Rush.Yds+Att+TD+X20.+X40.+Lng+Rush.1st+Rush.1st.+Rush.FUM,data=rush_train,kernel="radial",ranges=list(cost=c(0.1,1,10,100,1000),gamma=c(0.5,1,2,3,4)))
radial_bestmod=tune.out$best.model

#Compute Performance
predictions <- predict(radial_bestmod,rush_test)
my_roc <- roc(rush_test$pro_bowl, predictions)
best_roc <- coords(my_roc, "best", ret = "threshold")
SVM_conf <- confusionMatrix(as.factor(round(predictions+0.5-best_roc$threshold)),as.factor(rush_test$pro_bowl))

#LDA
lda_model = lda(pro_bowl~Rush.Yds+Att+TD+X20.+X40.+Lng+Rush.1st+Rush.1st.+Rush.FUM,data=rush_train)

#Compute Performance
lda_predictions <- predict(lda_model,rush_test)
lda_conf <- confusionMatrix(lda_predictions$class,as.factor(rush_test$pro_bowl))

#RF
RF <- randomForest(as.factor(pro_bowl)~Rush.Yds+Att+TD+X20.+X40.+Lng+Rush.1st+Rush.1st.+Rush.FUM,data=rush_train, method='class',ntree=1000)

#Compute Performance
RF_predictions <- predict(RF,rush_test,type='class')
RF_conf <- confusionMatrix(RF_predictions,as.factor(rush_test$pro_bowl))
```

```{r}
#Compute new pro bowl selections (Modify the lines below to test different models)
output <- predict(radial_bestmod,rushing_data)

output <- round(output + 0.5 - best_roc$threshold)
#output <- as.numeric(output$class)-1
#output <- as.numeric(output)-1

#Store player pro bowl selections
updated_rushing <- data.frame(Player = integer(length(rushing_data$Player)),pro_bowl = integer(length(rushing_data$pro_bowl)))
updated_rushing$Player <- rushing_data$Player
updated_rushing$pro_bowl <- output

rushing <- data.frame(Player = integer(length(updated_rushing$Player)),pro_bowl = integer(length(updated_rushing$pro_bowl)))
rushing$Player <- rushing_data$Player
rushing$pro_bowl <- rushing_data$pro_bowl

updated_rushing <- ddply(updated_rushing,~Player,summarise,pro_bowl=sum(pro_bowl))
rushing <- ddply(rushing,~Player,summarise,pro_bowl=sum(pro_bowl))

#Compare adjusted pro bowls to real pro bowls
rushing_diff <- data.frame(Player = integer(length(updated_rushing$Player)),pro_bowl = integer(length(updated_rushing$pro_bowl)))
rushing_diff$pro_bowl <-  updated_rushing$pro_bowl - rushing$pro_bowl
rushing_diff$Player <- rushing$Player
print(sum(rushing_diff$pro_bowl))
```

### Receiving

```{r}
#SVM (radial)
tune.out=tune(svm,pro_bowl~Rec+Yds+TD+X20.+X40.+LNG+Rec.1st+X1st.+Rec.FUM,data=receive_train,kernel="radial",ranges=list(cost=c(0.1,1,10,100,1000),gamma=c(0.5,1,2,3,4)))
radial_bestmod=tune.out$best.model

#Compute Performance
predictions <- predict(radial_bestmod,receive_test)
my_roc <- roc(receive_test$pro_bowl, predictions)
best_roc <- coords(my_roc, "best", ret = "threshold")
SVM_conf <- confusionMatrix(as.factor(round(predictions+0.1)),as.factor(receive_test$pro_bowl))

#LDA
lda_model = lda(pro_bowl~Rec+Yds+TD+X20.+X40.+LNG+Rec.1st+X1st.+Rec.FUM,data=receive_train)

#Compute Performance
lda_predictions <- predict(lda_model,receive_test)
lda_conf <- confusionMatrix(lda_predictions$class,as.factor(receive_test$pro_bowl))

#RF
RF <- randomForest(as.factor(pro_bowl)~Rec+Yds+TD+X20.+X40.+LNG+Rec.1st+X1st.+Rec.FUM,data=receive_train, method='class',ntree=1000)

#Compute Performance
RF_predictions <- predict(RF,receive_test,type='class')
RF_conf <- confusionMatrix(RF_predictions,as.factor(receive_test$pro_bowl))
```

```{r}
#Compute new pro bowl selections (Modify the lines below to test different models)
output <- predict(RF,receiving_data)

#output <- round(output+0.1)
#output <- as.numeric(output$class)-1
output <- as.numeric(output)-1

#Store player pro bowl selections
updated_receiving <- data.frame(Player = integer(length(receiving_data$Player)),pro_bowl = integer(length(receiving_data$pro_bowl)))
updated_receiving$Player <- receiving_data$Player
updated_receiving$pro_bowl <- output

receiving <- data.frame(Player = integer(length(updated_receiving$Player)),pro_bowl = integer(length(updated_receiving$pro_bowl)))
receiving$Player <- receiving_data$Player
receiving$pro_bowl <- receiving_data$pro_bowl

updated_receiving <- ddply(updated_receiving,~Player,summarise,pro_bowl=sum(pro_bowl))
receiving <- ddply(receiving,~Player,summarise,pro_bowl=sum(pro_bowl))

#Compare adjusted pro bowls to real pro bowls
receiving_diff <- data.frame(Player = integer(length(updated_receiving$Player)),pro_bowl = integer(length(updated_receiving$pro_bowl)))
receiving_diff$pro_bowl <-  updated_receiving$pro_bowl - receiving$pro_bowl
receiving_diff$Player <- receiving$Player
print(sum(receiving_diff$pro_bowl))
```